# Project information
site_name: Openterface | Conectando Interfaces a Novas Possibilidades
site_url: https://pt.openterface.com/
site_author: Billy Wang
site_description: Uma solução KVM-over-USB rica em recursos, de código aberto e impulsionada pela comunidade

# Repository
repo_name: Openterface
repo_url: https://github.com/TechxArtisanStudio/Openterface

# Copyright
copyright: >-
  Direitos autorais &copy; Todos os direitos reservados. 2023 <a href="https://www.openterface.com">Openterface</a> | <a href="https://www.techxartisan.com">TechxArtisan</a> | Guangzhou Billio Tech. Co., Ltd. <br>
  <a href="">Início</a> |
  <a href="/terms-of-service">Termos de Serviço</a> |
  <a href="/privacy-policy">Política de Privacidade</a> | 
  <a href="#__consent">Configurações de Cookies</a> | 
  <a href="/contact">Fale Conosco</a>

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: pt
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/app-logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - navigation.indexes
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
   - content.tabs.link

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  social:
    - icon: txa/crowd-supply-icon
      link: https://www.crowdsupply.com/techxartisan/openterface-mini-kvm
    - icon: fontawesome/brands/reddit-alien
      link: /reddit
    - icon: fontawesome/brands/discord
      link: /discord
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TechxArtisan
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TechxArtisan
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TechxArtisan
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/techxartisan/
  
  alternate:
    - name: English
      link: /
      lang: en
    - name: 简中文
      link: https://cn.openterface.com/
    - name: 日本語
      link: https://jp.openterface.com/
      lang: ja
    - name: 한국어
      link: https://kr.openterface.com/
      lang: ko
    - name: Français
      link: https://fr.openterface.com/
      lang: fr
    - name: Deutsch
      link: https://de.openterface.com/
      lang: de
    - name: Italiano
      link: https://it.openterface.com/
      lang: it
    - name: Español
      link: https://es.openterface.com/
      lang: es
      lang: zh
    - name: Português
      link: https://pt.openterface.com/
      lang: pt
    - name: Română
      link: https://ro.openterface.com/
      lang: ro
    
  consent:
    title: Consentimento de Cookies
    description: >- 
      Utilizamos cookies para melhorar a qualidade do conteúdo da documentação, analisar a eficácia do site e entender suas necessidades. 
      Ao consentir, você nos ajuda a aprimorar nosso site. Obrigado!
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-EKZEH6QYWT

markdown_extensions:
  # Enables tables
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
              custom_icons:
                - overrides/.icons
  - toc:
      permalink: ¶
      toc_depth: 3

plugins:
  - glightbox
  - search
  - redirects:
      redirect_maps:
        'basic-testing.md': 'basic.md'
        'community.md': 'https://www.reddit.com/r/Openterface_miniKVM/'
        'discord.md': 'https://discord.gg/sFTJD6a3R8'
        'reddit.md': 'https://www.reddit.com/r/Openterface_miniKVM/'
        'macos.md': 'https://github.com/TechxArtisanStudio/Openterface_MacOS'
        'android.md': 'https://github.com/TechxArtisanStudio/Openterface_Android'
        'qt.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'window.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'linux.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'hardware.md': 'https://github.com/TechxArtisanStudio/Openterface_Mini-KVM_Hardware'
        'feedback.md': 'https://forms.gle/YJLrCKwro8tbi6ar7'
        'oshw.md': 'https://certification.oshwa.org/cn000015.html'
        'x.md': 'https://x.com/TechxArtisan'
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{slug}"
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      categories_name: Categories
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      draft: true
      archive: false

nav:
  - Início: index.md
  - Documentação:
    - Início Rápido: quick-start.md
    - Funcionalidades: features.md
    - Como Conectar: how-to-connect.md
    - Software Aberto: app.md
    - Hardware Aberto: open-hardware.md
    - Controle Básico: basic.md
    - Porta USB Comutável: usb-switch.md
    - Pinos de Extensão: pin.md
    - Casos de Uso: use-cases.md
    - Especificações: specifications.md
    - O Que Vem na Caixa: whats-in-the-box.md
    - Acessórios: accessories.md
    - Como Funciona: how-it-works.md
    - Por Que Openterface: why-openterface.md
    - Comparação: comparison.md
    - Perguntas Frequentes: faq.md
    - Desenvolvimento:
      - Teste e Desenvolvimento: test.md
      - Roteiro: roadmap.md
      - Contribuindo: contributing.md
  - Perguntas Frequentes: /faq
  - Casos de Uso: /use-cases
  - Blog:
    - blog/index.md
  - Reddit: /reddit
  - Discord: /discord
  - Sobre:
    - Contato: contact.md
    - Políticas:
      - Política de Privacidade: privacy-policy.md
      - Termos de Serviço: terms-of-service.md
      - Devoluções, Reembolsos e Garantia: return-refunds-warranty.md