# Project information
site_name: Openterface | Conectando Interfaces a Novas Possibilidades
site_url: https://pt.openterface.com/
site_author: Openterface
site_description: Uma solução KVM-over-USB rica em recursos, de código aberto e impulsionada pela comunidade

# Repository
repo_name: Openterface_pt
repo_url: https://github.com/TechxArtisanStudio/Openterface_pt

# Copyright
copyright: >-
  Copyright &copy; Todos os direitos reservados. 2023 <a href="https://www.openterface.com">Openterface</a> | <a href="https://www.techxartisan.com">TechxArtisan</a><br>
  <a href="/">Início</a> |
  <a href="/policy/terms-of-service">Termos de Serviço</a> |
  <a href="/policy/privacy">Política de Privacidade</a> | 
  <a href="#__consent">Configurações de Cookies</a> | 
  <a href="/about">Sobre</a>
  
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/signup_form.css

extra_javascript:
  - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: pt
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/app-logo.png
  favicon: images/favicon.png
  icon:
    annotation: material/arrow-right-circle-outline
  features:
    - toc.integrate
    - toc.follow
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - last_updated

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  social:
    - icon: txa/crowd-supply-icon
      link: https://www.crowdsupply.com/techxartisan/openterface-mini-kvm
    - icon: fontawesome/brands/reddit-alien
      link: /reddit
    - icon: fontawesome/brands/discord
      link: /discord
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TechxArtisan
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TechxArtisan
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/TechxArtisan
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/techxartisan/
  
  alternate:
    - name: English
      link: https://openterface.com/
      lang: en
    - name: 简体中文
      lang: zh
      link: https://cn.openterface.com/
    - name: 日本語
      lang: ja
      link: https://jp.openterface.com/
    - name: 한국어
      lang: ko
      link: https://kr.openterface.com/
    - name: Français
      link: https://fr.openterface.com/
      lang: fr
    - name: Deutsch
      link: https://de.openterface.com/
      lang: de
    - name: Italiano
      link: https://it.openterface.com/
      lang: it
    - name: Español
      link: https://es.openterface.com/
      lang: es
    - name: Português
      link: https://pt.openterface.com/
      lang: pt
    - name: Română
      link: https://ro.openterface.com/
      lang: ro
    # - name: Svenska
    #   link: https://sv.openterface.com/
    #   lang: sv
    # - name: Polski
    #   link: https://pl.openterface.com/
    #   lang: pl
    # - name: Nederlands
    #   link: https://nl.openterface.com/
    #   lang: nl
    
  consent:
    title: Consentimento de Cookies
    description: >- 
      Utilizamos cookies para melhorar a qualidade do conteúdo da documentação, analisar a eficácia do site e entender suas necessidades. 
      Ao consentir, você nos ajuda a aprimorar nosso site. Obrigado!
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-EKZEH6QYWT

markdown_extensions:
  # Enables tables
  - tables
  # Enables admonitions
  - def_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
              custom_icons:
                - overrides/.icons
  - toc:
      toc_depth: 3

plugins:
  - glightbox
  - awesome-nav
  - search
  - macros
  - tags
  - meta
  # - git-committers:
  #     repository: TechxArtisanStudio/Openterface
  #     token: !ENV ['MK_SECRET_TOKEN']
  #     branch: main
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago  # or date
  - ultralytics:  # to enhance SEO by adding metadata
      verbose: True
      enabled: True
      default_author: "Openterface"
      add_desc: True
      add_image: True
      add_keywords: True
      add_share_buttons: False
      add_authors: False
      add_json_ld: False
      add_css: True
  - markdownextradata
  - redirects:
      redirect_maps:
        'buy-mini-kvm.md': 'https://www.crowdsupply.com/techxartisan/openterface-mini-kvm'
        'shop.md': 'https://shop.techxartisan.com'
        'reviews.md': 'product/minikvm/reviews.md'
        'features.md': 'product/minikvm/features.md'
        'why-openterface.md': 'faq/usbkvm/openterface.md'
        'webapp.md': 'https://openterface-viewer.pages.dev/'
        'faq/minikvm.md': 'faq/usbkvm/kvm-over-usb.md'
        'basic-testing.md': 'faq/usbkvm/kvm-over-usb.md'
        'dicord.md': 'https://discord.gg/sFTJD6a3R8'
        'usb-kvm.md': 'faq/usbkvm/kvm-over-usb.md'
        'usb-switch.md': 'product/minikvm/usb-switch.md'
        'product/minikvm/how-it-works.md': 'faq/usbkvm/kvm-over-usb.md'
        'how-it-works.md': 'faq/usbkvm/kvm-over-usb.md'
        'product.md': 'product/minikvm/index.md'
        'whats-in-the-box.md': 'product/minikvm/whats-in-the-box.md'
        'quick-start.md': 'product/minikvm/index.md'
        'open-hardware.md': 'https://github.com/TechxArtisanStudio/Openterface_Mini-KVM_Hardware'
        'basic/usb-switch.md': 'product/minikvm/usb-switch.md'
        'acknowledgements.md': 'contributing.md'
        'contact.md': 'about.md'
        'community.md': 'https://discord.gg/sFTJD6a3R8'
        'discord.md': 'https://discord.gg/sFTJD6a3R8'
        'reddit.md': 'https://www.reddit.com/r/Openterface_miniKVM/'
        'macos.md': 'https://github.com/TechxArtisanStudio/Openterface_MacOS'
        'android.md': 'https://github.com/TechxArtisanStudio/Openterface_Android'
        'qt.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'window.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'linux.md': 'https://github.com/TechxArtisanStudio/Openterface_QT'
        'hardware.md': 'https://github.com/TechxArtisanStudio/Openterface_Mini-KVM_Hardware'
        'feedback.md': 'https://forms.gle/YJLrCKwro8tbi6ar7'
        'oshw.md': 'https://certification.oshwa.org/cn000015.html'
        'x.md': 'https://x.com/TechxArtisan'
        'appstore.md': 'https://apps.apple.com/us/app/openterface-mini-kvm/id6478481082'
        'playstore.md': 'https://play.google.com/store/apps/details?id=com.openterface.AOS'
        'flathub.md': 'https://flathub.org/apps/com.openterface.openterfaceQT'
  - blog:
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      pagination: true
      pagination_per_page: 10
      draft: true
      archive: false