authors:
  TechxArtisan:
    name: TechxArtisan Studio
    description: Um estúdio criativo e comunidade de entusiastas de tecnologia.
    avatar: /images/txa-avatar.jpg

  Openterface:
    name: Openterface
    description: Olá!
    avatar: /images/op-avatar.jpg